events/urls.py
from django.urls import path
from django.conf import settings 
from django.conf.urls.static import static 
from .views import EventsView, event_detail

urlpatterns = [

    path('',EventsView.as_view( context_object_name = 'events'), name='events'),
    path('<int:id>/', event_detail, name='eventdetail'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/urls.py
from django.urls import path
from personal.views import home_view, blog, post_detail, mp3
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('', blog, name='blog' ),
    path('audio/<int:id>/', mp3, name='mp3'),
    path('<slug:slug>/', post_detail, name='detail'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personalweb/urls.py
from django.contrib import admin
from django.urls import path,include
from personal.views import home_view, blog
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_view, name='home'),
    path('blog/',include(('personal.urls', 'personal'), namespace='blog')),
    path('events/',include(('events.urls', 'events'), namespace='event')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models



class Location(models.Model):
   
    country = models.CharField(max_length=150)
    city = models.CharField(max_length=150)
    image = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.country

class Event(models.Model):
    event_name = models.CharField(max_length=150)
    event_description = models.TextField()
    event_location = models.CharField(max_length=200)
    event_datetime = models.DateTimeField()
    image = models.FileField(null=True, blank=True)
    views = models.CharField(blank=True, max_length=100)
    slug = models.SlugField(unique=True, max_length=100)
    location = models.ForeignKey(Location, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.event_name

personal/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Contact(models.Model):
    email = models.EmailField(max_length=250)
    message = models.TextField()

    def __str__(self):
        return self.email

class Post(models.Model):
    title = models.CharField(max_length=150)
    category = models.CharField(max_length=200)
    description = models.TextField()
    published = models.DateTimeField(default=timezone.now())
    image = models.FileField(null=True, blank=True)
    views = models.CharField(blank=True, max_length=100)
    slug = models.SlugField(unique=True, max_length=100)

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug}) 
         

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=250)
    comment = models.TextField()
    date = models.DateField(default=timezone.now())

    def __str__(self):
        return self.comment
    

personal/forms.py
from django import forms
from .models import Contact,Comment


class AttendForm(forms.ModelForm):
   


    class Meta:
        model=Contact
        fields=[
            'email',
            'message',
        ]

class CommentForm(forms.ModelForm):

    class Meta:
        model=Comment
        fields=[
            'name',
            'email',
            'comment',

]         

events/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.list import ListView
from urllib.parse import quote_plus
from django.db.models import F,Count
from django.http import JsonResponse
from .models import Event, Location

def event_detail(request,id):
    location = get_object_or_404(Location, id=id)
    events = Event.objects.filter(location=location)
    template = "event_detail.html"
    context = {
        'location':location,
        'events':events
    }

    return render(request, template, context)

class EventsView(ListView):
    model = Location
    paginate_by = 2
    context_object_name = 'events'
    template_name = 'events.html'

personal/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404,redirect, HttpResponseRedirect
from .models import Contact, Post, Comment
from django.db.models import F,Count
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from gtts import gTTS
from django.core.files.storage import FileSystemStorage
import os
from django.utils.html import strip_tags


def home_view(request):
    if request.method =="POST": 
        email = request.POST.get('email')
        message = request.POST.get('message')

        Contact.objects.create(
            email = email,
            message = message,
        ) 

        return HttpResponse()
    posts = Post.objects.all()[:3]    
    context = {
        'posts':posts,
    }
    template = "home.html"
    return render(request, template, context)


def mp3(request,id):
    post = get_object_or_404(Post, id=id)
    folder='media/' 
    mytext = post.description
    stripped = strip_tags(mytext)
    mp3name = post.slug
    language = 'en'
    myobj = gTTS(text=stripped, lang=language, slow=False)   
    myobj.save(os.path.join('media', mp3name + ".mp3"))
    return HttpResponseRedirect(post.get_absolute_url())


def blog(request):
    if request.method =="POST": 
        email = request.POST.get('email')
        message = request.POST.get('message')
       
        Contact.objects.create(
            email = email,
            message = message,
        ) 

        return HttpResponse('')
   
    posts = Post.objects.all().order_by('-published')
    query = request.GET.get('q')
    if query:
       posts = posts.filter(title__icontains=query)
    
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    if not page:
        page = paginator.num_pages
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context={
        'posts':posts,
    }   
    template = "blog.html" 
    return render(request, template, context)


def post_detail(request, slug):
    
    post = get_object_or_404(Post, slug=slug)
    response_data = {}  
 

    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        comment = request.POST.get('comment')
        date = request.POST.get('date')

        response_data['name'] = name
        response_data['comment'] = comment
        response_data['date'] = date
      
        Comment.objects.create(
            name = name,
            email = email,
            comment = comment,
            post = post,
  
        )
        return JsonResponse(response_data)
    posts = Post.objects.all()
    query = request.GET.get('q')
    if query:
       posts = posts.filter(title__icontains=query)
    comments = Comment.objects.filter(post=post)
    commentss = Comment.objects.filter(post=post).annotate(book_count=Count('comment'))
    Post.objects.filter(id=post.id).update(views=F('views') + 1)
    context = {
        'post':post,
        'posts':posts,
        'comments':comments,
        'commentss':commentss,
    }
    template = "detail.html"
    return render(request, template, context)

templates/blog.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="/static/img/fullstack_astronaut.png">
    <meta name="title" content="FullStack Astronaut">
    <meta name="author" content="fullstack astronaut">
    <meta name="description" content="{{post.description|truncatewords:150|safe}}">
    <meta property="og:url" content="fullstackastronaut.com/blog/">
    <meta property="og:type" content="website">
    <meta property="og:image" content="/static/img/fullstack_astronaut.png">
    <meta name="keywords" content="django, python, what is django, react.js, how to build website, power of python, fullstackastronaut.com">
    <meta charset="UTF-8">
    <title>Blog</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> 
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/linearicons.css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/magnific-popup.css">
    <link rel="stylesheet" href="/static/css/nice-select.css">	
    <link rel="stylesheet" href="/static/css/hexagons.min.css">							
    <link rel="stylesheet" href="/static/css/animate.min.css">
    <link rel="stylesheet" href="/static/css/owl.carousel.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-135529058-1"></script>
    <script>
       window.dataLayer = window.dataLayer || [];
       function gtag(){dataLayer.push(arguments);}
       gtag('js', new Date());

       gtag('config', 'UA-135529058-1');
      </script>
    </head>
    <body>	
          <header id="header" id="home">
            <div class="container main-menu">
                <div class="row align-items-center justify-content-between d-flex">
                  <div id="logo">
                    <a href="{% url 'home'%}"><img src="/static/img/fullstack_astronaut.png" width="50rem" alt="logo" title="" /></a>                 
                 </div>
                 <nav id="nav-menu-container">
                        <ul class="nav-menu">
                          <li class="menu-active"><a href="{% url 'home' %}">Home</a></li>
                          <li><a href="{% url 'blog:blog' %}">Blog</a></li>
                          <li><a href="{% url 'event:events'%}">Events</a></li>
                          
                        </ul>
                      </nav>      	    		
                </div>
            </div>
          </header>
          
        <section class="banner-area relative" id="home">	
            <div class="container">
                <div class="row d-flex align-items-center justify-content-center">
                    <div class="about-content col-lg-12">
                        <h1 id="reduce" class="text-white">
                            Work hard, help others & success will follow
                            			
                        </h1>	
                        <p class="text-white link-nav"><a href="index.html">Infinity</a>  <span class="fas fa-rocket"></span>  <a href="blog-home.html"> Beyond </a></p>
                    </div>											
                </div>
            </div>
        </section>
        
        <section class="blog-posts-area section-gap">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 post-list blog-post-list">
                            <label for="theme" class="switchSmall m5">
                                    <p>Switch Theme</p>
                                <input id="theme" type="checkbox">
                                <small></small>
                                </label>
                        {% for post in posts %}
                        <div class="single-post">
                                <a href="{% url 'blog:detail' post.slug %}">
                            <img class="img-fluid blog-scifi" src="/media/{{post.image}}" alt="{{post.title}}">
                                </a>
                            <a href="{% url 'blog:detail' post.slug %}">
                                <h1 id="reduce">
                                    {{post.title}}
                                </h1>
                                <p>{{post.category}}</p>
                            </a>
                                <p>
                                    {{post.description|truncatewords:7|safe}}
                                </p>
                            <div class="bottom-meta">
                                <div class="user-details row align-items-center">
                                    <div class="comment-wrap col-lg-12">
                                        <ul>
                                            <li><a href="#"><span class="fas fa-eye details-row" style="color:#a015f5;"></span> <p  class="details-row">{{post.views}}</p></a></li>
                                            <li><a href="#"><span class="fas fa-calendar-week details-row" style="color:#a015f5;"></span> <p  class="details-row">{{post.published}}</p> </a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="paginator">
                        {% if posts.has_other_pages %}
                         <ul class="pagination my-4">
                            {% for i in posts.paginator.page_range %}
                              {% if posts.number == i %}
                                 <li class="active page-btn" style="margin:2px;"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                              {% else %}
                                  <li><a class="page-btn" href="?page={{ i }}" style="margin:2px;">{{ i }}</a></li>
                              {% endif %}
                            {% endfor %}
             
                         </ul>
                        {% endif %}
                        </div>																					
                    </div>
                    <div class="col-lg-4 sidebar">
                        <div class="single-widget search-widget">
                            <form class="example"role="search" method="GET" action="">
                                <label for="search">Search</label>
                              <input id="search" type="text" placeholder="Search Posts" name="q">
                              <button type="submit"><strong class="fa fa-search"></strong></button>
                            </form>								
                        </div>

                        <div class="single-widget protfolio-widget">
                            <img src="/static/img/avatar-fa.jpg"  width="40%" style="border-radius: 50%" alt="avatar">
                            <a href="#"><h4 style="color:rgb(55, 56, 56)">coderasha</h4></a>
                            <p>
                                    I am a fullstack_astronaut with a vast array of knowledge in many different front end and back end languages, responsive frameworks, databases, and best code practices.
                                     My objective is simply to communicate with the other web astronaust.
                                      I am dedicated to perfecting my craft by learning from more seasoned developers, remaining humble, and continuously launching DevRockets to learn all that
                                       I can about development.
                            </p>							
                        </div>

                       

                    </div>
                </div>
            </div>	
        </section>
        
        <footer class="footer-area section-gap">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4 col-md-12">
                            <div class="single-footer-widget">
                                <h6>Stay Connected!</h6>
                                <ul class="footer-nav">
                                    Join me! Let's discover web space together!<br>
                                    Challenges coming soon.
                                    
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-6  col-md-12">
                            <div class="single-footer-widget newsletter">
                               
                                <h6>Contact with me!</h6>
                                <p>I will reply to your email!</p>
                                <div id="mc_embed_signup">
                                    <form method="POST" class="form-inline" id="contact-form">
                                         {% csrf_token %}
                                        <div class="form-group row" style="width: 100%">
                                                <div class="col-lg-8 col-md-12">
                                                        <label style="float: left" for="email">Email</label>
                                                        <input id="email" name="EMAIL" class="my-2" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">
                                                        <label style="float: left" for="message">Message</label>
                                                        <textarea id="message" name="MESSAGE"class="my-2" placeholder="Enter Message" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" ></textarea>
                                                    </div>    
                                        </div>	
                                        
                                        <button id="send" type="submit" class="send-btn"></button>	
                                        
                                    </form>
                                    
                                </div>		
                            </div>
                        </div>
                        <div class="col-lg-2  col-md-12 footer-social">
                            <a href="https://twitter.com/coderasha" target="_blank"><strong class="fa fa-twitter"></strong></a>
                            <a href="https://instagram.com/coderasha"  target="_blank"><strong class="fa fa-instagram"></strong></a>
                        </div>						
                    </div>
    
                    <div class="row footer-bottom d-flex justify-content-between">
                        <p class="col-lg-8 col-sm-12 footer-text m-0 text-white">
     &copy;<script>document.write(new Date().getFullYear());</script> | FullStack Astronaut 
    </p>     
                    </div>
                </div>
            </footer>
        <script src="/static/js/vendor/jquery-2.2.4.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="/static/js/vendor/bootstrap.min.js"></script>			
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
          <script src="/static/js/easing.min.js"></script>			
        <script src="/static/js/hoverIntent.js"></script>
        <script src="/static/js/superfish.min.js"></script>	
        <script src="/static/js/jquery.ajaxchimp.min.js"></script>
        <script src="/static/js/jquery.magnific-popup.min.js"></script>	
        <script src="/static/js/owl.carousel.min.js"></script>	
        <script src="/static/js/hexagons.min.js"></script>							
        <script src="/static/js/jquery.nice-select.min.js"></script>	
        <script src="/static/js/jquery.counterup.min.js"></script>
        <script src="/static/js/waypoints.min.js"></script>							
        <script src="/static/js/mail-script.js"></script>	
        <script src="/static/js/main.js"></script>	
        <script src="/static/js/ajax-calls.js"></script>
    </body>
</html>

templates/events.html
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="#">
    <meta name="author" content="codepixer">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="UTF-8">
    <title>Fullstack Astronaut</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> 
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/linearicons.css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/magnific-popup.css">
    <link rel="stylesheet" href="/static/css/nice-select.css">	
    <link rel="stylesheet" href="/static/css/hexagons.min.css">							
    <link rel="stylesheet" href="/static/css/animate.min.css">
    <link rel="stylesheet" href="/static/css/owl.carousel.css">
    <link rel="stylesheet" href="/static/css/main.css">
    </head>
    <body>	
        <header id="header" id="home">
            <div class="container main-menu">
                <div class="row align-items-center justify-content-between d-flex">
                  <div id="logo">
                    <a href="{% url 'home'%}"><img src="/static/img/fullstack_astronaut.png" width="50rem" alt="logo" title="" /></a>                 
                 </div>
                 <nav id="nav-menu-container">
                        <ul class="nav-menu">
                          <li class="menu-active"><a href="{% url 'home' %}">Home</a></li>
                          <li><a href="{% url 'blog:blog' %}">Blog</a></li>
                          <li><a href="{% url 'event:events'%}">Events</a></li>
                          
                        </ul>
                      </nav>      	    		
                </div>
            </div>
          </header>

          <section class="banner-area relative" id="home">	
            <div class="container">
                <div class="row d-flex align-items-center justify-content-center">
                    <div class="about-content col-lg-12">
                        <h1 id="reduce" class="text-white">
                            Work hard, help others & success will follow
                            			
                        </h1>	
                        <p class="text-white link-nav">Infinity  <span class="fas fa-rocket"></span> Beyond</p>
                    </div>											
                </div>
            </div>
        </section>

        

        <!-- Start home-about Area -->
        <section class="home-about-area">
            <div class="container-fluid">
                    <div class="row align-items-center infinite-container"> 
                    {% for event in events %}
                    <div class="col-lg-6 infinite-item">
                        <a href="{% url 'events:eventdetail' event.id%}">
                        <div class="item">
                            <img class="mx-auto d-block img-fluid " src="/media/{{event.image}}" alt="{{event.country}}">
                            <h2 class="title card">{{event.country}}</h2>
                        </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
                {% if page_obj.has_next %}
                    <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
                {% endif %}
                
               <div class="one my-5" style="display:none;">
                
                </div>
                
            </div>	
        </section>
        <section class="footer my-5">
                
            <p class="col-lg-12 footer-text my-5 " style="color:rgb(0, 0, 0); text-align: center">
&copy;<script>document.write(new Date().getFullYear());</script> Fullstack Astronaut | Events 
</p>     
       

    </section>
       

	

        <script src="/static/js/vendor/jquery-2.2.4.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="/static/js/vendor/bootstrap.min.js"></script>			
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
          <script src="/static/js/easing.min.js"></script>			
        <script src="/static/js/hoverIntent.js"></script>
        <script src="/static/js/superfish.min.js"></script>	
        <script src="/static/js/jquery.ajaxchimp.min.js"></script>
        <script src="/static/js/jquery.magnific-popup.min.js"></script>	
        <script src="/static/js/owl.carousel.min.js"></script>	
        <script src="/static/js/hexagons.min.js"></script>							
        <script src="/static/js/jquery.nice-select.min.js"></script>	
        <script src="/static/js/jquery.counterup.min.js"></script>
        <script src="/static/js/waypoints.min.js"></script>	
        <script src="/static/js/infinite.min.js"></script>							
        <script src="/static/js/mail-script.js"></script>	
        <script src="/static/js/main.js"></script>
        <script src="/static/js/jquery.waypoints.min.js"></script>
        <script src="/static/js/infinite.min.js"></script>
        <script>
                var infinite = new Waypoint.Infinite({
                  element: $('.infinite-container')[0],
                 
                  
                  
                });

              </script>
       


    </body>
</html>